# Generated by Django 3.1.1 on 2020-10-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliahSaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('dosen', models.CharField(max_length=50)),
                ('jumlahSKS', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('ruangKelas', models.CharField(max_length=10)),
            ],
        ),
    ]
