# Generated by Django 3.1.1 on 2020-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliahsaya',
            name='deskripsi',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
