# Generated by Django 3.1.1 on 2020-10-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0002_matakuliahsaya_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahsaya',
            name='dosen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliahsaya',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliahsaya',
            name='ruangKelas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliahsaya',
            name='semester',
            field=models.CharField(max_length=100),
        ),
    ]
