# Generated by Django 3.1.1 on 2020-10-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
