# Generated by Django 3.1.1 on 2020-10-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatansaya',
            name='NamaKegiatan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
