# Generated by Django 3.1.1 on 2020-10-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story6', '0002_auto_20201020_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatansaya',
            name='NamaKegiatan',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
